#Applied Data Science: NumPy Basics (by Atul Bhardwaj)
##What is NumPy?##

NumPy is the fundamental package for scientific computing with Python. It contains among other things:

- a powerful N-dimensional array object
- sophisticated (broadcasting) functions
- tools for integrating C/C++ and Fortran code
- useful linear algebra, Fourier transform, and random number capabilities

Source: http://www.numpy.org/

##Important Resources##

**User Manual**: http://docs.scipy.org/doc/numpy/user/index.html <br>
**Reference**: http://docs.scipy.org/doc/numpy/reference/index.html

**Check your NumPy version to make sure manual is not outdated**

In [1]:
import numpy as np

np.__version__

'1.9.2'

###List vs Array##

The main different between the two is that list allows mixed data type, while array only allows homogeneous data

In [2]:
lst = list([10, 20, 30, 'remove the end character'])

In [3]:
lst[0]*5, lst[-1].rstrip('r')

(50, 'remove the end characte')

In [4]:
arr = np.array(lst) #convert to array
arr[0]*5

'1010101010'

It repeated the element 5 times; performed a string operation instead of a mathematical one. Hence, the array is treating 
all elements like strings

**Checking the data type of the array**

In [5]:
np.array([1,2,3]).dtype

dtype('int32')

###Matrices vs Array

Conceptually there are a lot of similarities, and arrays allow many matrices functions to be performed seamlessly. The major difference (in terms of mathematical operations) is that arrays feature broadcasting, while certain mathematical operations on matrices of different sizes are undefined. For example adding matrices of unequal sizes. However, we can bind arrays to same laws by converting arrays to the matrices objects.

###Creating arrays easily

In [6]:
np.zeros(5, dtype='int64') #all zero array

array([0, 0, 0, 0, 0], dtype=int64)

In [7]:
np.ones(5, dtype='int') #all ones array

array([1, 1, 1, 1, 1])

**Multi-dimensional Array**

In [8]:
arr = np.arange(0,100,10).reshape(5,2) #arange: Return evenly spaced values within a given interval.
print (arr.ndim)
arr

2


array([[ 0, 10],
       [20, 30],
       [40, 50],
       [60, 70],
       [80, 90]])

In [9]:
print ( arr.reshape(1,5,2).ndim )
arr.reshape(1,5,2)

3


array([[[ 0, 10],
        [20, 30],
        [40, 50],
        [60, 70],
        [80, 90]]])

##Taste of Universal Functions
**What are ufunc?**<br>
A universal function (or ufunc for short) is a function that operates on ndarrays in an element-by-element fashion, supporting array broadcasting, type casting, and several other standard features. That is, a ufunc is a “vectorized” wrapper for a function that takes a fixed number of scalar inputs and produces a fixed number of scalar outputs.


### Accumulate

In [10]:
arr = np.linspace(1, 10, 10).reshape(5,2)
arr

array([[  1.,   2.],
       [  3.,   4.],
       [  5.,   6.],
       [  7.,   8.],
       [  9.,  10.]])

In [11]:
np.add.accumulate(arr, axis=0) #Cumulative along column

array([[  1.,   2.],
       [  4.,   6.],
       [  9.,  12.],
       [ 16.,  20.],
       [ 25.,  30.]])

###Reduce

In [12]:
np.add.reduce(arr, axis=0) #Column Totals only

array([ 25.,  30.])

In [13]:
#alternative (but NOT a ufunc)
arr.sum(axis=0) #unfunc is faster

array([ 25.,  30.])

More on Universal Functions: http://docs.scipy.org/doc/numpy/reference/ufuncs.html

##List of array Methods
An array object has many methods which operate on or with the array in some fashion, typically returning an array result, 
here's a complete list. To quickly learn more, you can use the '?' help feature of jupyter(IPython):

    arr.T             arr.copy          arr.getfield      arr.put           arr.squeeze
    arr.all           arr.ctypes        arr.imag          arr.ravel         arr.std
    arr.any           arr.cumprod       arr.item          arr.real          arr.strides
    arr.argmax        arr.cumsum        arr.itemset       arr.repeat        arr.sum
    arr.argmin        arr.data          arr.itemsize      arr.reshape       arr.swapaxes
    arr.argsort       arr.diagonal      arr.max           arr.resize        arr.take
    arr.astype        arr.dot           arr.mean          arr.round         arr.tofile
    arr.base          arr.dtype         arr.min           arr.searchsorted  arr.tolist
    arr.byteswap      arr.dump          arr.nbytes        arr.setasflat     arr.tostring
    arr.choose        arr.dumps         arr.ndim          arr.setfield      arr.trace
    arr.clip          arr.fill          arr.newbyteorder  arr.setflags      arr.transpose
    arr.compress      arr.flags         arr.nonzero       arr.shape         arr.var
    arr.conj          arr.flat          arr.prod          arr.size          arr.view
    arr.conjugate     arr.flatten       arr.ptp           arr.sort          